name: Deploy REPO

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks
        env:
          DATABRICKS_HOST_DEV: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_TOKEN_DEV: ${{ secrets.DATABRICKS_TOKEN_DEV }}
        run: |
          mkdir -p ~/.databricks

          cat > ~/.databrickscfg << EOF
          [DEFAULT]
          host=$DATABRICKS_HOST_DEV
          token=$DATABRICKS_TOKEN_DEV
          EOF

      - name: Import REPO Folder
        run: |
          databricks workspace import_dir . /LIVE_dev

      - name: Verify Deployment
        run: |
          echo "===== ROOT ====="
          databricks workspace ls /

          echo "===== LIVE_dev ====="
          databricks workspace ls /LIVE_dev
  
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref_name=='main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks
        env:
          DATABRICKS_HOST_PROD: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN_PROD: ${{ secrets.DATABRICKS_TOKEN_PROD }}
        run: |
          mkdir -p ~/.databricks

          cat > ~/.databrickscfg << EOF
          [DEFAULT]
          host=$DATABRICKS_HOST_PROD
          token=$DATABRICKS_TOKEN_PROD
          EOF

      - name: Import REPO Folder
        run: |
          databricks workspace import_dir . /LIVE_prod

      - name: Verify Deployment
        run: |
          echo "===== ROOT ====="
          databricks workspace ls /

          echo "===== LIVE_prod ====="
          databricks workspace ls /LIVE_prod

